print("Welcome to the tip calculator")
bill = float(input("What was the total bill ? $"))
cent = int(input("What percentage tip would you like to give ? 10, 12, or 15? "))
people = int(input("How many people to split the bill? "))
tip = bill * (cent/100)
amount = (bill/people)+(tip/people)
a = "{:.2f}".format(amount)
print(f"Each person should pay: ${a}")
